//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This code was auto-generated by Microsoft.VisualStudio.ServiceReference.Platforms, version 12.0.21005.1
// 
namespace OnlineVideosWin81.Services.OnlineVideoService {
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="BlogInfo", Namespace="http://schemas.datacontract.org/2004/07/OnlineVideosService")]
    public partial class BlogInfo : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string BlogTypeField;
        
        private string PasswordField;
        
        private string UserNameField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string BlogType {
            get {
                return this.BlogTypeField;
            }
            set {
                if ((object.ReferenceEquals(this.BlogTypeField, value) != true)) {
                    this.BlogTypeField = value;
                    this.RaisePropertyChanged("BlogType");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Password {
            get {
                return this.PasswordField;
            }
            set {
                if ((object.ReferenceEquals(this.PasswordField, value) != true)) {
                    this.PasswordField = value;
                    this.RaisePropertyChanged("Password");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string UserName {
            get {
                return this.UserNameField;
            }
            set {
                if ((object.ReferenceEquals(this.UserNameField, value) != true)) {
                    this.UserNameField = value;
                    this.RaisePropertyChanged("UserName");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Favorites", Namespace="http://schemas.datacontract.org/2004/07/OnlineVideosService")]
    public partial class Favorites : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string _AnonymousIdField;
        
        private string _ApplicationNameField;
        
        private int _HstatusField;
        
        private int _IdField;
        
        private string _LastUpdatedField;
        
        private string _LinkTypeField;
        
        private int _favouriteField;
        
        private string _historyMovienameField;
        
        private int _historycountField;
        
        private int _historyidField;
        
        private int _movieIdField;
        
        private string _ratingField;
        
        private string _removeField;
        
        private string _songnoField;
        
        private int _statusField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string _AnonymousId {
            get {
                return this._AnonymousIdField;
            }
            set {
                if ((object.ReferenceEquals(this._AnonymousIdField, value) != true)) {
                    this._AnonymousIdField = value;
                    this.RaisePropertyChanged("_AnonymousId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string _ApplicationName {
            get {
                return this._ApplicationNameField;
            }
            set {
                if ((object.ReferenceEquals(this._ApplicationNameField, value) != true)) {
                    this._ApplicationNameField = value;
                    this.RaisePropertyChanged("_ApplicationName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int _Hstatus {
            get {
                return this._HstatusField;
            }
            set {
                if ((this._HstatusField.Equals(value) != true)) {
                    this._HstatusField = value;
                    this.RaisePropertyChanged("_Hstatus");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int _Id {
            get {
                return this._IdField;
            }
            set {
                if ((this._IdField.Equals(value) != true)) {
                    this._IdField = value;
                    this.RaisePropertyChanged("_Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string _LastUpdated {
            get {
                return this._LastUpdatedField;
            }
            set {
                if ((object.ReferenceEquals(this._LastUpdatedField, value) != true)) {
                    this._LastUpdatedField = value;
                    this.RaisePropertyChanged("_LastUpdated");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string _LinkType {
            get {
                return this._LinkTypeField;
            }
            set {
                if ((object.ReferenceEquals(this._LinkTypeField, value) != true)) {
                    this._LinkTypeField = value;
                    this.RaisePropertyChanged("_LinkType");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int _favourite {
            get {
                return this._favouriteField;
            }
            set {
                if ((this._favouriteField.Equals(value) != true)) {
                    this._favouriteField = value;
                    this.RaisePropertyChanged("_favourite");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string _historyMoviename {
            get {
                return this._historyMovienameField;
            }
            set {
                if ((object.ReferenceEquals(this._historyMovienameField, value) != true)) {
                    this._historyMovienameField = value;
                    this.RaisePropertyChanged("_historyMoviename");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int _historycount {
            get {
                return this._historycountField;
            }
            set {
                if ((this._historycountField.Equals(value) != true)) {
                    this._historycountField = value;
                    this.RaisePropertyChanged("_historycount");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int _historyid {
            get {
                return this._historyidField;
            }
            set {
                if ((this._historyidField.Equals(value) != true)) {
                    this._historyidField = value;
                    this.RaisePropertyChanged("_historyid");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int _movieId {
            get {
                return this._movieIdField;
            }
            set {
                if ((this._movieIdField.Equals(value) != true)) {
                    this._movieIdField = value;
                    this.RaisePropertyChanged("_movieId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string _rating {
            get {
                return this._ratingField;
            }
            set {
                if ((object.ReferenceEquals(this._ratingField, value) != true)) {
                    this._ratingField = value;
                    this.RaisePropertyChanged("_rating");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string _remove {
            get {
                return this._removeField;
            }
            set {
                if ((object.ReferenceEquals(this._removeField, value) != true)) {
                    this._removeField = value;
                    this.RaisePropertyChanged("_remove");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string _songno {
            get {
                return this._songnoField;
            }
            set {
                if ((object.ReferenceEquals(this._songnoField, value) != true)) {
                    this._songnoField = value;
                    this.RaisePropertyChanged("_songno");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int _status {
            get {
                return this._statusField;
            }
            set {
                if ((this._statusField.Equals(value) != true)) {
                    this._statusField = value;
                    this.RaisePropertyChanged("_status");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Rating", Namespace="http://schemas.datacontract.org/2004/07/OnlineVideosService")]
    public partial class Rating : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int _IdField;
        
        private int _movieIdField;
        
        private string _ratingField;
        
        private string _ratingdateField;
        
        private string _songnoField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int _Id {
            get {
                return this._IdField;
            }
            set {
                if ((this._IdField.Equals(value) != true)) {
                    this._IdField = value;
                    this.RaisePropertyChanged("_Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int _movieId {
            get {
                return this._movieIdField;
            }
            set {
                if ((this._movieIdField.Equals(value) != true)) {
                    this._movieIdField = value;
                    this.RaisePropertyChanged("_movieId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string _rating {
            get {
                return this._ratingField;
            }
            set {
                if ((object.ReferenceEquals(this._ratingField, value) != true)) {
                    this._ratingField = value;
                    this.RaisePropertyChanged("_rating");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string _ratingdate {
            get {
                return this._ratingdateField;
            }
            set {
                if ((object.ReferenceEquals(this._ratingdateField, value) != true)) {
                    this._ratingdateField = value;
                    this.RaisePropertyChanged("_ratingdate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string _songno {
            get {
                return this._songnoField;
            }
            set {
                if ((object.ReferenceEquals(this._songnoField, value) != true)) {
                    this._songnoField = value;
                    this.RaisePropertyChanged("_songno");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="OnlineVideoService.IOnlineVideoService")]
    public interface IOnlineVideoService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IOnlineVideoService/GetUsernameandPassword", ReplyAction="http://tempuri.org/IOnlineVideoService/GetUsernameandPasswordResponse")]
        System.Threading.Tasks.Task<System.Collections.ObjectModel.ObservableCollection<OnlineVideosWin81.Services.OnlineVideoService.BlogInfo>> GetUsernameandPasswordAsync(string Category, string ApplicationName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IOnlineVideoService/SendMail", ReplyAction="http://tempuri.org/IOnlineVideoService/SendMailResponse")]
        System.Threading.Tasks.Task<bool> SendMailAsync(string from, string To, string Subject, string Body);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IOnlineVideoService/InsertUserData", ReplyAction="http://tempuri.org/IOnlineVideoService/InsertUserDataResponse")]
        System.Threading.Tasks.Task InsertUserDataAsync(System.Collections.ObjectModel.ObservableCollection<OnlineVideosWin81.Services.OnlineVideoService.Favorites> fav);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IOnlineVideoService/RetrieveuserData", ReplyAction="http://tempuri.org/IOnlineVideoService/RetrieveuserDataResponse")]
        System.Threading.Tasks.Task<System.Collections.ObjectModel.ObservableCollection<OnlineVideosWin81.Services.OnlineVideoService.Favorites>> RetrieveuserDataAsync(string AnonymousId, string ApplicationName, int Id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IOnlineVideoService/InsertParentalControlData", ReplyAction="http://tempuri.org/IOnlineVideoService/InsertParentalControlDataResponse")]
        System.Threading.Tasks.Task InsertParentalControlDataAsync(System.Collections.ObjectModel.ObservableCollection<OnlineVideosWin81.Services.OnlineVideoService.Favorites> fav);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IOnlineVideoService/RetrieveParentalControlData", ReplyAction="http://tempuri.org/IOnlineVideoService/RetrieveParentalControlDataResponse")]
        System.Threading.Tasks.Task<System.Collections.ObjectModel.ObservableCollection<OnlineVideosWin81.Services.OnlineVideoService.Favorites>> RetrieveParentalControlDataAsync(string AnonymousId, string ApplicationName, int Id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IOnlineVideoService/GetRating", ReplyAction="http://tempuri.org/IOnlineVideoService/GetRatingResponse")]
        System.Threading.Tasks.Task<System.Collections.ObjectModel.ObservableCollection<OnlineVideosWin81.Services.OnlineVideoService.Favorites>> GetRatingAsync(System.Collections.ObjectModel.ObservableCollection<OnlineVideosWin81.Services.OnlineVideoService.Favorites> fav);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IOnlineVideoService/GetSearchHistory", ReplyAction="http://tempuri.org/IOnlineVideoService/GetSearchHistoryResponse")]
        System.Threading.Tasks.Task<System.Collections.ObjectModel.ObservableCollection<OnlineVideosWin81.Services.OnlineVideoService.Favorites>> GetSearchHistoryAsync(System.Collections.ObjectModel.ObservableCollection<OnlineVideosWin81.Services.OnlineVideoService.Favorites> fav);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IOnlineVideoService/RetrievevideosratingControlData", ReplyAction="http://tempuri.org/IOnlineVideoService/RetrievevideosratingControlDataResponse")]
        System.Threading.Tasks.Task<System.Collections.ObjectModel.ObservableCollection<OnlineVideosWin81.Services.OnlineVideoService.Favorites>> RetrievevideosratingControlDataAsync(string ApplicationName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IOnlineVideoService/GetRatingvideos", ReplyAction="http://tempuri.org/IOnlineVideoService/GetRatingvideosResponse")]
        System.Threading.Tasks.Task<System.Collections.ObjectModel.ObservableCollection<OnlineVideosWin81.Services.OnlineVideoService.Favorites>> GetRatingvideosAsync(System.Collections.ObjectModel.ObservableCollection<OnlineVideosWin81.Services.OnlineVideoService.Favorites> fav);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IOnlineVideoService/getRatingnextupdateddate", ReplyAction="http://tempuri.org/IOnlineVideoService/getRatingnextupdateddateResponse")]
        System.Threading.Tasks.Task<System.Collections.ObjectModel.ObservableCollection<OnlineVideosWin81.Services.OnlineVideoService.Rating>> getRatingnextupdateddateAsync(string rdate, string ApplicationName, int Id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IOnlineVideoService/getRatingVideosnextupdateddate", ReplyAction="http://tempuri.org/IOnlineVideoService/getRatingVideosnextupdateddateResponse")]
        System.Threading.Tasks.Task<System.Collections.ObjectModel.ObservableCollection<OnlineVideosWin81.Services.OnlineVideoService.Rating>> getRatingVideosnextupdateddateAsync(string rdate, string ApplicationName, int Id);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IOnlineVideoServiceChannel : OnlineVideosWin81.Services.OnlineVideoService.IOnlineVideoService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class OnlineVideoServiceClient : System.ServiceModel.ClientBase<OnlineVideosWin81.Services.OnlineVideoService.IOnlineVideoService>, OnlineVideosWin81.Services.OnlineVideoService.IOnlineVideoService {
        
        /// <summary>
        /// Implement this partial method to configure the service endpoint.
        /// </summary>
        /// <param name="serviceEndpoint">The endpoint to configure</param>
        /// <param name="clientCredentials">The client credentials</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public OnlineVideoServiceClient() : 
                base(OnlineVideoServiceClient.GetDefaultBinding(), OnlineVideoServiceClient.GetDefaultEndpointAddress()) {
            this.Endpoint.Name = EndpointConfiguration.CustomBinding_IOnlineVideoService.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public OnlineVideoServiceClient(EndpointConfiguration endpointConfiguration) : 
                base(OnlineVideoServiceClient.GetBindingForEndpoint(endpointConfiguration), OnlineVideoServiceClient.GetEndpointAddress(endpointConfiguration)) {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public OnlineVideoServiceClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(OnlineVideoServiceClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress)) {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public OnlineVideoServiceClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(OnlineVideoServiceClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress) {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public OnlineVideoServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public System.Threading.Tasks.Task<System.Collections.ObjectModel.ObservableCollection<OnlineVideosWin81.Services.OnlineVideoService.BlogInfo>> GetUsernameandPasswordAsync(string Category, string ApplicationName) {
            return base.Channel.GetUsernameandPasswordAsync(Category, ApplicationName);
        }
        
        public System.Threading.Tasks.Task<bool> SendMailAsync(string from, string To, string Subject, string Body) {
            return base.Channel.SendMailAsync(from, To, Subject, Body);
        }
        
        public System.Threading.Tasks.Task InsertUserDataAsync(System.Collections.ObjectModel.ObservableCollection<OnlineVideosWin81.Services.OnlineVideoService.Favorites> fav) {
            return base.Channel.InsertUserDataAsync(fav);
        }
        
        public System.Threading.Tasks.Task<System.Collections.ObjectModel.ObservableCollection<OnlineVideosWin81.Services.OnlineVideoService.Favorites>> RetrieveuserDataAsync(string AnonymousId, string ApplicationName, int Id) {
            return base.Channel.RetrieveuserDataAsync(AnonymousId, ApplicationName, Id);
        }
        
        public System.Threading.Tasks.Task InsertParentalControlDataAsync(System.Collections.ObjectModel.ObservableCollection<OnlineVideosWin81.Services.OnlineVideoService.Favorites> fav) {
            return base.Channel.InsertParentalControlDataAsync(fav);
        }
        
        public System.Threading.Tasks.Task<System.Collections.ObjectModel.ObservableCollection<OnlineVideosWin81.Services.OnlineVideoService.Favorites>> RetrieveParentalControlDataAsync(string AnonymousId, string ApplicationName, int Id) {
            return base.Channel.RetrieveParentalControlDataAsync(AnonymousId, ApplicationName, Id);
        }
        
        public System.Threading.Tasks.Task<System.Collections.ObjectModel.ObservableCollection<OnlineVideosWin81.Services.OnlineVideoService.Favorites>> GetRatingAsync(System.Collections.ObjectModel.ObservableCollection<OnlineVideosWin81.Services.OnlineVideoService.Favorites> fav) {
            return base.Channel.GetRatingAsync(fav);
        }
        
        public System.Threading.Tasks.Task<System.Collections.ObjectModel.ObservableCollection<OnlineVideosWin81.Services.OnlineVideoService.Favorites>> GetSearchHistoryAsync(System.Collections.ObjectModel.ObservableCollection<OnlineVideosWin81.Services.OnlineVideoService.Favorites> fav) {
            return base.Channel.GetSearchHistoryAsync(fav);
        }
        
        public System.Threading.Tasks.Task<System.Collections.ObjectModel.ObservableCollection<OnlineVideosWin81.Services.OnlineVideoService.Favorites>> RetrievevideosratingControlDataAsync(string ApplicationName) {
            return base.Channel.RetrievevideosratingControlDataAsync(ApplicationName);
        }
        
        public System.Threading.Tasks.Task<System.Collections.ObjectModel.ObservableCollection<OnlineVideosWin81.Services.OnlineVideoService.Favorites>> GetRatingvideosAsync(System.Collections.ObjectModel.ObservableCollection<OnlineVideosWin81.Services.OnlineVideoService.Favorites> fav) {
            return base.Channel.GetRatingvideosAsync(fav);
        }
        
        public System.Threading.Tasks.Task<System.Collections.ObjectModel.ObservableCollection<OnlineVideosWin81.Services.OnlineVideoService.Rating>> getRatingnextupdateddateAsync(string rdate, string ApplicationName, int Id) {
            return base.Channel.getRatingnextupdateddateAsync(rdate, ApplicationName, Id);
        }
        
        public System.Threading.Tasks.Task<System.Collections.ObjectModel.ObservableCollection<OnlineVideosWin81.Services.OnlineVideoService.Rating>> getRatingVideosnextupdateddateAsync(string rdate, string ApplicationName, int Id) {
            return base.Channel.getRatingVideosnextupdateddateAsync(rdate, ApplicationName, Id);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync() {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        public virtual System.Threading.Tasks.Task CloseAsync() {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginClose(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndClose));
        }
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration) {
            if ((endpointConfiguration == EndpointConfiguration.CustomBinding_IOnlineVideoService)) {
                System.ServiceModel.Channels.CustomBinding result = new System.ServiceModel.Channels.CustomBinding();
                System.ServiceModel.Channels.TextMessageEncodingBindingElement textBindingElement = new System.ServiceModel.Channels.TextMessageEncodingBindingElement();
                result.Elements.Add(textBindingElement);
                System.ServiceModel.Channels.HttpTransportBindingElement httpBindingElement = new System.ServiceModel.Channels.HttpTransportBindingElement();
                httpBindingElement.AllowCookies = true;
                httpBindingElement.MaxBufferSize = int.MaxValue;
                httpBindingElement.MaxReceivedMessageSize = int.MaxValue;
                result.Elements.Add(httpBindingElement);
                return result;
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration) {
            if ((endpointConfiguration == EndpointConfiguration.CustomBinding_IOnlineVideoService)) {
                return new System.ServiceModel.EndpointAddress("http://onlinevideoswin8service.lartsoft.com/OnlineVideoService.svc");
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.Channels.Binding GetDefaultBinding() {
            return OnlineVideoServiceClient.GetBindingForEndpoint(EndpointConfiguration.CustomBinding_IOnlineVideoService);
        }
        
        private static System.ServiceModel.EndpointAddress GetDefaultEndpointAddress() {
            return OnlineVideoServiceClient.GetEndpointAddress(EndpointConfiguration.CustomBinding_IOnlineVideoService);
        }
        
        public enum EndpointConfiguration {
            
            CustomBinding_IOnlineVideoService,
        }
    }
}
